name: CI

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - run: npm ci

    - name: Build
      run: npm run build

    - name: run tests
      run: npm run test

    - name: Create coverage report
      run: npm run report-coveralls

    - name: Upload coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
